### ISSUE TITLE
Request for Dockerfiles for Isaac ROS Images

### ISSUE THREAD

**Issue by osama-z-salah** [nvidia-isaac/isaac_mission_dispatch#12]
I'm working with the Isaac ROS Docker images (nvcr.io/nvidia/isaac/mission-database:isaac_ros and nvcr.io/nvidia/isaac/mission-dispatch:isaac_ros) and need to rebuild them after some modifications. However, I can't find the Dockerfiles. Could you point me to these files or provide them if available?

Thanks for your help!

**Comment by nv-delliott** [comment]
Base containers are in `/docker`, bazel is used to build & tag them.  You can inspect the bazel files here: `https://github.com/nvidia-isaac/isaac_mission_dispatch/tree/main/bzl`
Enter the developer container:
`https://github.com/nvidia-isaac/isaac_mission_dispatch#launch-mission-dispatch-services-locally`
```
bazel build ...
bazel run -- packages/controllers/mission/mission-img-bundle && docker tag bazel_image mission-dispatch
bazel run -- packages/database/postgres-img-bundle && docker tag bazel_image mission-database
```

Let us know if that doesn't work for you.  Verify to originator, issue will be closed in 2 weeks if not verified.
