### ISSUE TITLE
Use docker compose instead of docker-compose in documentation

### ISSUE THREAD

**Issue by dchatarpaul** [nvidia-isaac/isaac_mission_dispatch#2]
Using docker-compose to deploy the containers will result in an error on the latest available version of that package I could get through apt. Using docker compose which is specified in the official docker documentation: https://docs.docker.com/compose/reference/ allows the services to startup properly. 

Here is the error I was seeing using the documentation specified in this repo:

`~/isaac_mission_dispatch/docker_compose$ docker-compose -f mission_dispatch_services.yaml up
ERROR: The Compose file './mission_dispatch_services.yaml' is invalid because:
services.mission-database.depends_on contains an invalid type, it should be an array`

And here is a list of the versions of docker I have on my system:

`$ dpkg -l | grep docker
ii  docker-ce                                  5:20.10.21~3-0~ubuntu-focal                                                     amd64        Docker: the open-source application container engine
ii  docker-ce-cli                              5:20.10.21~3-0~ubuntu-focal                                                     amd64        Docker CLI: the open-source application container engine
ii  docker-ce-rootless-extras                  5:20.10.18~3-0~ubuntu-focal                                                     amd64        Rootless support for Docker.
ii  docker-compose                             1.25.0-1                                                                        all          Punctual, lightweight development environments using Docker
ii  docker-compose-plugin                      2.12.2~ubuntu-focal                                                             amd64        Docker Compose (V2) plugin for the Docker CLI.
ii  docker-scan-plugin                         0.17.0~ubuntu-focal                                                             amd64        Docker scan cli plugin.
ii  python3-docker                             4.1.0-1                                                                         all          Python 3 wrapper to access docker.io's control socket
ii  python3-dockerpty                          0.4.1-2                                                                         all          Pseudo-tty handler for docker Python client (Python 3.x)
`

**Comment by nv-delliott** [comment]
Resolved this and a few other errors in documentation in PR !4 https://github.com/nvidia-isaac/isaac_mission_dispatch/pull/4
Please verify and thanks for helping improve the code!
