### ISSUE TITLE
No documentation on how to run kubernetes containers after installation

### ISSUE THREAD

**Issue by dchatarpaul** [nvidia-isaac/isaac_mission_dispatch#6]
Hello! 

I've run through the kubernetes instructions successfully however I'm not sure what kubectl commands should be executed to run the mosquitto, mission-dispatch, postgres and mission-database applications? It should be documented and users can copy and paste the commands to get going with Isaac mission dispatch.

**Comment by nv-delliott** [comment]
To get going with Kubernetes and Mission Dispatch, you can get started here https://github.com/nvidia-isaac/isaac_mission_dispatch#deploy-with-kubernetes .  We'll add more documentation to that in a future release.  Docker / Docker Compose are the easiest to use and understand at present.
